name: vlm
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.3.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arxiv==2.1.3
      - asttokens==3.0.0
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.3.0
      - babel==2.16.0
      - bcrypt==4.2.1
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.45.0
      - black==24.10.0
      - bleach==6.2.0
      - blinker==1.9.0
      - brotli==1.1.0
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - coverage==7.6.10
      - cryptography==44.0.0
      - cycler==0.12.1
      - datasets==3.2.0
      - debugpy==1.8.12
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.16.2
      - defusedxml==0.7.1
      - diffusers==0.32.2
      - dill==0.3.8
      - distro==1.9.0
      - duckduckgo-search==5.3.1b1
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - execnet==2.1.1
      - executing==2.1.0
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - feedparser==6.0.11
      - ffmpy==0.5.0
      - filelock==3.13.1
      - flash-attn==2.7.3
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - func-timeout==4.3.5
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==4.42.0
      - gradio-client==1.3.0
      - griffe==0.49.0
      - h11==0.12.0
      - h2==4.1.0
      - hf-doc-builder==0.5.0
      - hjson==3.1.0
      - hpack==4.0.0
      - httpcore==0.15.0
      - httpx==0.24.1
      - huggingface-hub==0.27.1
      - hydra-core==1.3.2
      - hyperframe==6.0.1
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.3
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lagent==0.2.4
      - lazy-loader==0.4
      - linkify-it-py==2.0.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mistune==3.1.0
      - mmcv==2.2.0
      - mmdet==3.3.0
      - mmengine==0.10.6
      - mpi4py-mpich==3.1.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - narwhals==1.22.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.10.15
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - paramiko==3.5.0
      - parso==0.8.4
      - pathspec==0.12.1
      - peft==0.14.1.dev0
      - pexpect==4.9.0
      - phx-class-registry==4.1.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pynacl==1.5.0
      - pyparsing==3.2.1
      - pytest==8.3.4
      - pytest-cov==6.0.0
      - pytest-xdist==3.6.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruff==0.6.9
      - safetensors==0.5.2
      - scikit-image==0.25.0
      - scipy==1.15.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - setuptools==65.5.1
      - sgmllib3k==1.0.0
      - shapely==2.0.6
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.41.3
      - streamlit==1.41.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - termcolor==2.5.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - tifffile==2025.1.10
      - tiktoken==0.8.0
      - timeout-decorator==0.5.0
      - timm==1.0.9
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.3.1+cu118
      - torchaudio==2.3.1+cu118
      - torchvision==0.18.1+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.44.2
      - transformers-stream-generator==0.0.5
      - triton==2.3.1
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - widgetsnbextension==4.0.13
      - xtuner==0.1.23
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /home/linshan/anaconda3/envs/vlm
